config:  # main config (in this file) overrides additional configs
  additional:  # add additional config file paths --- the order matters (later ones overwrite previous ones, then the main config (this file) overwrites them, and finally the command line arguments overwrite all)
  - configs/defaults/shared.yaml
  - configs/defaults/train.yaml

special:
  extra_name: template  # null for no extra name

info:
  output_dir: ./outputs/template/
  project_name: template

data:
  dataset: simple
  split_rate: 0.8

model:
  model_choice: simple
  backbone: default

criterion:
  criterion_choice: default  # default as 'model.model_choice'
  loss: mse
  primary_criterion: null  # null (None) to use loss as primary_criterion
  primary_criterion_higher_better: False  # XXX: important for choosing best model

trainer:
  ## batch_control
  trainer_batch_size_per_rank: 32
  sync_lr_with_batch_size: 0  # XXX: if > 0, sync lr with batchsize (lr_real = lr_config * batch_size_total[all_ranks, grad_accumulation] / sync_lr_with_batch_size)
  ## batch_control ends
  trainer_choice: default
  pretrained_models: null  # None or a dict of pretrained models {name1: path1, name2: path2, ...}
  load_from_ema: True
  epochs: 10
  real_epochs: null  # if not None, do early stopping based on real_epochs (scheduler is still based on epochs)
  optimizer:
    optimizer_choice: adamw  # adamw, sgd
    sgd_momentum: 0.9
    lr_default: 4.0e-4
    wd_default: 1.0e-2
    # param_groups:  # xx_name means if string 'name' in named_parameters, use these xx settings
    #   lr_backbone: 4.0e-4
    #   wd_backbone: 1.0e-2
    #   lr_head: 1.0e-4
    #   wd_head: 1.0e-4
    max_grad_norm: 1.0  # <= 0 means no gradient clipping
    freeze_modules: []  # [submodule_name1, submodule_name2, ...], '.' can be used to point to a subsubmodule
    lr_scheduler:
      ### len(phase) == N, e.g. N=2: warmup, keep
      lr_phase_epochs: [10]  # (N-1) the last phase goes to the end
      lr_phase_steps: [50]  # (N-1) the last phase goes to the end; if phase_steps is not null, override phase_epochs
      lr_phase_scales: [0.0, 1.0, 0.001]  # (N+1) start scale of each phase and the final scale of the end
      lr_phase_types: [linear, cosine]  # (N)
    wd_scheduler:
      ### len(phase) == N, e.g. N=2: warmup, keep
      wd_phase_epochs: []  # (N-1) the last phase goes to the end
      wd_phase_steps: null  # (N-1) the last phase goes to the end; if phase_steps is not null, override phase_epochs
      wd_phase_scales: [1.0, 1.0]  # (N+1) start scale of each phase and the final scale of the end
      wd_phase_types: [keep_start]  # (N)

sweep:
  sweep_enabled: False
  sweep_params:  # use '//' as the connector for sub-params
    trainer//optimizer//lr_default: [2.0e-4, 4.0e-4]
