config: TBD  # config file name, will be overwritten by sacred

# deepspeed:
#   ds_enable: True

special:
  debug: False
  save_current_project: False  # maybe always False in inference
  print_save_config_ignore: [sweep]
  wandb_config_ignore: [info, sweep, special]

data:
  batch_size_per_rank: 1

info:
  task_type: Infer  # Test, Infer, ...
  wandb_watch_model: False
  wandb_watch_freq: 100
  cli_log_freq: 1
  # wandb_log_freq: 10  # NO NEED. only one epoch with few iters
  wandb_buffer_time: 300  # seconds
  # global_tqdm: True  # NO NEED. only one epoch
  
env:
  device: cuda
  gpu: TBD
  distributed: TBD
  dist_url: env://
  dist_backend: TBD
  world_size: TBD
  rank: TBD

tester:
  use_best: True
  save_images: True
  checkpoint_path: TBD
  train_cfg_path: ./outputs/2023-10-13-11-02-32_simple_simple_mse_32/cfg.yaml  # XXX: required

sweep:
  sweep_enabled: False
  sweep_params:  # use '-' as connect symbols for sub-params 
    data-batch_size_per_rank: [1, 2]
